image: openjdk:10-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - apt-get update
  - chmod +x gradlew

test:
  stage: test
  script: 
    - ./gradlew --build-cache assemble
    - ./gradlew check